<?php
/**
 * Generated by Haxe 4.3.7
 */

namespace wphx\fixtures\wp\core;

use \php\Boot;

class NativeValueLoweringProofEntry {
	/**
	 * @param \StdClass $value
	 *
	 * @return bool
	 */
	public static function isRowObject ($value) {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/NativeValueLoweringProofEntry.hx:16: characters 3-35
		return \is_object($value);
	}

	/**
	 * @return void
	 */
	public static function main () {
	}

	/**
	 * @param \StdClass $row
	 *
	 * @return array
	 */
	public static function rowFields ($row) {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/NativeValueLoweringProofEntry.hx:21: characters 3-38
		return \get_object_vars($row);
	}

	/**
	 * @param array $values
	 *
	 * @return mixed[]
	 */
	public static function rowValues ($values) {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/NativeValueLoweringProofEntry.hx:26: characters 3-39
		return \array_values($values);
	}

	/**
	 * @param array $values
	 *
	 * @return mixed
	 */
	public static function shiftFirst (&$values) {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/NativeValueLoweringProofEntry.hx:31: characters 3-38
		return \array_shift($values);
	}
}

Boot::registerClass(NativeValueLoweringProofEntry::class, 'wphx.fixtures.wp.core.NativeValueLoweringProofEntry');
