<?php
/**
 * Generated by Haxe 4.3.7
 */

namespace wphx\fixtures\wp\core;

use \php\Boot;

class PublicClassLoweringSubject extends PublicClassLoweringBase implements PublicClassLoweringContract {
	/**
	 * @var int
	 */
	static public $instances = 0;

	/**
	 * @var int
	 */
	public $metaCount;
	/**
	 * @var string
	 */
	public $name;

	/**
	 * @param string $name
	 *
	 * @return PublicClassLoweringSubject
	 */
	public static function factory ($name) {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/PublicClassLoweringProofEntry.hx:44: characters 3-49
		return new PublicClassLoweringSubject($name, 1);
	}

	/**
	 * @param string $name
	 * @param int $metaCount
	 *
	 * @return void
	 */
	public function __construct ($name, $metaCount = 0) {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/PublicClassLoweringProofEntry.hx:35: lines 35-40
		if ($metaCount === null) {
			$metaCount = 0;
		}
		#fixtures/wp-core/src/wphx/fixtures/wp/core/PublicClassLoweringProofEntry.hx:36: characters 3-24
		parent::__construct("base-" . ($name??'null'));
		#fixtures/wp-core/src/wphx/fixtures/wp/core/PublicClassLoweringProofEntry.hx:37: characters 3-19
		$this->name = $name;
		#fixtures/wp-core/src/wphx/fixtures/wp/core/PublicClassLoweringProofEntry.hx:38: characters 3-29
		$this->metaCount = $metaCount;
		#fixtures/wp-core/src/wphx/fixtures/wp/core/PublicClassLoweringProofEntry.hx:39: characters 3-14
		PublicClassLoweringSubject::$instances++;
	}

	/**
	 * @return string
	 */
	public function describe () {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/PublicClassLoweringProofEntry.hx:49: characters 3-32
		return ($this->name??'null') . ":" . ($this->metaCount??'null');
	}
}

Boot::registerClass(PublicClassLoweringSubject::class, 'wphx.fixtures.wp.core.PublicClassLoweringSubject');
