<?php
/**
 * Generated by Haxe 4.3.7
 */

namespace wphx\fixtures\wp\core;

use \php\Boot;

interface PublicClassLoweringContract {
	/**
	 * @return string
	 */
	public function describe () ;
}

Boot::registerClass(PublicClassLoweringContract::class, 'wphx.fixtures.wp.core.PublicClassLoweringContract');
